apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-app

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: observability
  app.kubernetes.io/part-of: oci-observability-overview
  app.kubernetes.io/managed-by: kustomize

# Override image with your OCIR registry. Example:
#   kustomize edit set image observability-app=fra.ocir.io/NAMESPACE/observability-app:v1.0
images:
  - name: observability-app
    newName: observability-app
    newTag: latest
