# GOADv3 Terraform Variables — adapted for Seven Kingdoms Portal.
#
# Defaults target eu-frankfurt-1 with oci4cca profile.
# Override via terraform.tfvars (auto-generated by deploy_goad.sh).

variable "tenancy_ocid" {
  description = "OCI tenancy OCID"
  type        = string
  default     = ""
}

variable "compartment_ocid" {
  description = "OCI compartment OCID"
  type        = string
}

variable "region" {
  description = "OCI region"
  type        = string
  default     = "eu-frankfurt-1"
}

variable "oci_profile" {
  description = "OCI config profile name"
  type        = string
  default     = "DEFAULT"
}

variable "availability_domain" {
  description = "Availability domain for instances"
  type        = string
}

variable "ssh_authorized_keys" {
  description = "SSH public key for Linux instances"
  type        = string
}

# --- VM Shapes ---

variable "windows_shape" {
  description = "Shape for Windows VMs"
  type        = string
  default     = "VM.Standard.E5.Flex"
}

variable "windows_ocpus" {
  description = "OCPUs for Windows VMs"
  type        = number
  default     = 2
}

variable "windows_memory_gbs" {
  description = "Memory (GB) for Windows VMs"
  type        = number
  default     = 32
}

variable "jumpbox_shape" {
  description = "Shape for jumpbox"
  type        = string
  default     = "VM.Standard.E5.Flex"
}

variable "jumpbox_ocpus" {
  description = "OCPUs for jumpbox"
  type        = number
  default     = 1
}

variable "jumpbox_memory_gbs" {
  description = "Memory (GB) for jumpbox"
  type        = number
  default     = 12
}

# --- Image OCIDs (eu-frankfurt-1) ---

variable "jumpbox_image_ocid" {
  description = "Oracle Linux / Ubuntu image OCID for jumpbox"
  type        = string
  # Ubuntu 22.04 Minimal aarch64 (eu-frankfurt-1) — update as needed
  default     = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaxroekfbow3kdrdjlwao6tsxxfcb23xmqrdjtjcay2ow52eijvzqa"
}

variable "windows2016_image_ocid" {
  description = "Windows Server 2016 image OCID"
  type        = string
  default     = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaae2knsz2v5pfsmfahfesqfcxbbtybhtucwxpq7c2lsvi3ouc5aira"
}

variable "windows2019_image_ocid" {
  description = "Windows Server 2019 image OCID"
  type        = string
  default     = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaq55esthgeydsqq5esexgu3numtsltsfkalqjcee6jit47kwv2vva"
}

# --- Peering ---

variable "app_vcn_id" {
  description = "App VCN OCID for LPG peering (from C1 infrastructure)"
  type        = string
  default     = ""
}

variable "app_lpg_id" {
  description = "App-side LPG OCID to peer with (from C1 infrastructure)"
  type        = string
  default     = ""
}

# --- Tags ---

variable "freeform_tags" {
  description = "Freeform tags for resources"
  type        = map(string)
  default = {
    project = "seven-kingdoms-portal"
    component = "goad"
  }
}
