"""APM Detection Rules for Seven Kingdoms Portal Vulnerability Spans.

Each rule maps to a specific attack type generated by the vulnerable portal.
Rules can be:
  - Queried via the /portal/api/detection-rules endpoint
  - Imported into OCI Log Analytics as saved searches
  - Used in OCI Monitoring alarms for real-time alerting
  - Referenced in the Control Plane detection coverage dashboard

OCI APM Trace Explorer query syntax:
  show (spans) SpanName as Name, ...
  where SpanAttribute['security.attack.detected'] = 'true'
  AND SpanAttribute['security.attack.type'] = 'sqli'
"""
from __future__ import annotations

DETECTION_RULES: list[dict] = [
    # ── A01: Broken Access Control ─────────────────────────────────
    {
        "id": "SKP-001",
        "name": "IDOR — Unauthorized User Profile Access",
        "severity": "high",
        "mitre_id": "T1078",
        "mitre_tactic": "privilege-escalation",
        "owasp": "A01:2021",
        "attack_type": "idor",
        "description": "User accessed another user's profile by manipulating the ID parameter.",
        "apm_query": (
            "show (spans) SpanName as Name, "
            "SpanAttribute['security.attack.type'] as AttackType, "
            "SpanAttribute['security.username'] as User, "
            "SpanAttribute['security.source_ip'] as SourceIP "
            "where SpanAttribute['security.attack.type'] = 'idor'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'idor' "
            "| stats count as attack_count by security_source_ip, security_username "
            "| where attack_count > 3"
        ),
        "portal_endpoints": ["/portal/api/users/{id}", "/portal/api/treasury/{id}"],
    },
    {
        "id": "SKP-002",
        "name": "Path Traversal — Directory Escape Attempt",
        "severity": "critical",
        "mitre_id": "T1083",
        "mitre_tactic": "discovery",
        "owasp": "A01:2021",
        "attack_type": "path_traversal",
        "description": "Request contained path traversal sequences (../) to access files outside the allowed directory.",
        "apm_query": (
            "show (spans) SpanName as Name, "
            "SpanAttribute['security.attack.payload'] as Payload "
            "where SpanAttribute['security.attack.type'] = 'path_traversal'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'path_traversal' "
            "| stats count as traversal_count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/files/download"],
    },
    {
        "id": "SKP-003",
        "name": "Open Redirect — URL Manipulation",
        "severity": "medium",
        "mitre_id": "T1566.002",
        "mitre_tactic": "initial-access",
        "owasp": "A01:2021",
        "attack_type": "open_redirect",
        "description": "Application redirected to an external URL controlled by the attacker.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as RedirectURL "
            "where SpanAttribute['security.attack.type'] = 'open_redirect'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'open_redirect' "
            "| stats count by security_attack_payload"
        ),
        "portal_endpoints": ["/portal/api/redirect"],
    },
    # ── A02: Cryptographic Failures ────────────────────────────────
    {
        "id": "SKP-004",
        "name": "Credential Exposure — Debug Endpoint Leak",
        "severity": "critical",
        "mitre_id": "T1552",
        "mitre_tactic": "credential-access",
        "owasp": "A02:2021",
        "attack_type": "credential_leak",
        "description": "Sensitive cryptographic material (JWT secret, encryption keys) exposed via debug endpoint.",
        "apm_query": (
            "show (spans) SpanName as Name, "
            "SpanAttribute['security.source_ip'] as SourceIP "
            "where SpanAttribute['security.attack.type'] = 'credential_leak'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'credential_leak' "
            "| stats earliest(security_attack_timestamp) as first_seen, "
            "count as leak_count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/debug/crypto", "/portal/api/users?debug=true"],
    },
    # ── A03: Injection ─────────────────────────────────────────────
    {
        "id": "SKP-005",
        "name": "SQL Injection — Treasury Database Query",
        "severity": "critical",
        "mitre_id": "T1190",
        "mitre_tactic": "initial-access",
        "owasp": "A03:2021",
        "attack_type": "sqli",
        "description": "SQL injection payload detected in treasury search parameter. May extract financial records.",
        "apm_query": (
            "show (spans) SpanName as Name, "
            "SpanAttribute['security.attack.payload'] as SQLPayload, "
            "SpanAttribute['security.source_ip'] as SourceIP "
            "where SpanAttribute['security.attack.type'] = 'sqli'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'sqli' "
            "| where security_attack_payload like '%OR%1%=%1%' "
            "or security_attack_payload like '%UNION%SELECT%' "
            "| stats count as sqli_count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/treasury/search"],
    },
    {
        "id": "SKP-006",
        "name": "Command Injection — OS Command Execution",
        "severity": "critical",
        "mitre_id": "T1059",
        "mitre_tactic": "execution",
        "owasp": "A03:2021",
        "attack_type": "rce",
        "description": "Arbitrary OS command executed on the server via command injection vulnerability.",
        "apm_query": (
            "show (spans) SpanName as Name, "
            "SpanAttribute['security.attack.payload'] as Command "
            "where SpanAttribute['security.attack.type'] = 'rce'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'rce' "
            "| stats count as rce_count by security_attack_payload, security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/command/exec"],
    },
    {
        "id": "SKP-007",
        "name": "Server-Side Template Injection (SSTI)",
        "severity": "critical",
        "mitre_id": "T1059",
        "mitre_tactic": "execution",
        "owasp": "A03:2021",
        "attack_type": "ssti",
        "description": "Template injection payload rendered server-side, potentially leading to RCE.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as Template "
            "where SpanAttribute['security.attack.type'] = 'ssti'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'ssti' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/template/render"],
    },
    {
        "id": "SKP-008",
        "name": "LDAP Injection — Directory Query Manipulation",
        "severity": "high",
        "mitre_id": "T1190",
        "mitre_tactic": "initial-access",
        "owasp": "A03:2021",
        "attack_type": "ldap_injection",
        "description": "LDAP filter injection in user lookup query against GOAD Active Directory.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as LDAPFilter "
            "where SpanAttribute['security.attack.type'] = 'ldap_injection'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'ldap_injection' "
            "| stats count by security_source_ip, security_username"
        ),
        "portal_endpoints": ["/portal/api/ldap/lookup"],
    },
    {
        "id": "SKP-009",
        "name": "Stored XSS — Message Payload Injection",
        "severity": "high",
        "mitre_id": "T1059.007",
        "mitre_tactic": "execution",
        "owasp": "A03:2021",
        "attack_type": "xss",
        "description": "Cross-site scripting payload stored in message system, executed on other users' browsers.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as XSSPayload "
            "where SpanAttribute['security.attack.type'] = 'xss'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'xss' "
            "| where security_attack_payload like '%<script%' "
            "or security_attack_payload like '%onerror%' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/messages/send"],
    },
    # ── A04: Insecure Design ──────────────────────────────────────
    {
        "id": "SKP-010",
        "name": "Mass Assignment — Privilege Escalation via Registration",
        "severity": "high",
        "mitre_id": "T1098",
        "mitre_tactic": "persistence",
        "owasp": "A04:2021",
        "attack_type": "mass_assignment",
        "description": "User registered with elevated role by including 'role' field in registration payload.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as Payload "
            "where SpanAttribute['security.attack.type'] = 'mass_assignment'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'mass_assignment' "
            "| stats count by security_username"
        ),
        "portal_endpoints": ["/portal/api/auth/register"],
    },
    # ── A05: Security Misconfiguration ────────────────────────────
    {
        "id": "SKP-011",
        "name": "Security Misconfiguration — Crypto Config Disclosure",
        "severity": "high",
        "mitre_id": "T1552",
        "mitre_tactic": "credential-access",
        "owasp": "A05:2021",
        "attack_type": "credential_leak",
        "description": "Debug endpoint exposed JWT secrets, encryption keys, and crypto configuration.",
        "apm_query": (
            "show (spans) SpanName as Name "
            "where SpanName like 'ATTACK:CREDENTIAL_LEAK'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'credential_leak' "
            "| stats count as access_count by security_source_ip "
            "| where access_count > 1"
        ),
        "portal_endpoints": ["/portal/api/debug/crypto", "/portal/api/debug/env"],
    },
    # ── A07: Authentication Failures ──────────────────────────────
    {
        "id": "SKP-012",
        "name": "Default Credentials — Admin Login with Well-Known Password",
        "severity": "critical",
        "mitre_id": "T1078",
        "mitre_tactic": "defense-evasion",
        "owasp": "A07:2021",
        "attack_type": "auth_bypass",
        "description": "Successful login using default admin/admin credentials.",
        "apm_query": (
            "show (spans) SpanAttribute['security.username'] as User "
            "where SpanAttribute['security.attack.type'] = 'auth_bypass'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'auth_bypass' "
            "| stats count by security_username, security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/auth/login"],
    },
    {
        "id": "SKP-013",
        "name": "Brute Force — Multiple Failed Login Attempts",
        "severity": "high",
        "mitre_id": "T1110",
        "mitre_tactic": "credential-access",
        "owasp": "A07:2021",
        "attack_type": "brute_force",
        "description": "Multiple failed login attempts detected from the same source within a short window.",
        "apm_query": (
            "show (spans) SpanAttribute['security.source_ip'] as SourceIP, "
            "SpanAttribute['security.username'] as User "
            "where SpanAttribute['security.attack.type'] = 'brute_force'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'brute_force' "
            "| stats count as attempts by security_source_ip "
            "| where attempts >= 5"
        ),
        "portal_endpoints": ["/portal/api/auth/login"],
    },
    {
        "id": "SKP-014",
        "name": "JWT None Algorithm — Token Signature Bypass",
        "severity": "critical",
        "mitre_id": "T1134",
        "mitre_tactic": "privilege-escalation",
        "owasp": "A07:2021",
        "attack_type": "jwt_manipulation",
        "description": "JWT token submitted with 'none' algorithm, bypassing signature verification.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as JWTHeader "
            "where SpanAttribute['security.attack.type'] = 'jwt_manipulation'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'jwt_manipulation' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/admin/panel"],
    },
    # ── A08: Software and Data Integrity Failures ─────────────────
    {
        "id": "SKP-015",
        "name": "Insecure Deserialization — Pickle/JSON Import",
        "severity": "critical",
        "mitre_id": "T1059",
        "mitre_tactic": "execution",
        "owasp": "A08:2021",
        "attack_type": "deserialization",
        "description": "Untrusted data deserialized via pickle or unsafe JSON import, risking RCE.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as Payload "
            "where SpanAttribute['security.attack.type'] = 'deserialization'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'deserialization' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/import/profile", "/portal/api/import/json"],
    },
    # ── A09: Security Logging and Monitoring Failures ─────────────
    {
        "id": "SKP-016",
        "name": "Log Injection — Log Forging Attack",
        "severity": "medium",
        "mitre_id": "T1070",
        "mitre_tactic": "defense-evasion",
        "owasp": "A09:2021",
        "attack_type": "log_injection",
        "description": "Malicious content injected into application logs to forge entries or confuse analysis.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as InjectedLog "
            "where SpanAttribute['security.attack.type'] = 'log_injection'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'log_injection' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/log"],
    },
    # ── A10: Server-Side Request Forgery ──────────────────────────
    {
        "id": "SKP-017",
        "name": "SSRF — Internal Network Scanning via Avatar Fetch",
        "severity": "critical",
        "mitre_id": "T1090",
        "mitre_tactic": "command-and-control",
        "owasp": "A10:2021",
        "attack_type": "ssrf",
        "description": "Server-side request forged to internal network addresses via avatar URL parameter.",
        "apm_query": (
            "show (spans) SpanAttribute['security.attack.payload'] as TargetURL "
            "where SpanAttribute['security.attack.type'] = 'ssrf'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'ssrf' "
            "| where security_attack_payload like '%169.254%' "
            "or security_attack_payload like '%127.0.0%' "
            "or security_attack_payload like '%10.0.%' "
            "| stats count by security_attack_payload, security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/avatar/fetch", "/portal/api/webhook/test"],
    },
    # ── GOAD-Specific Attack Simulations ──────────────────────────
    {
        "id": "SKP-018",
        "name": "Kerberoasting — SPN Ticket Extraction",
        "severity": "critical",
        "mitre_id": "T1558.003",
        "mitre_tactic": "credential-access",
        "owasp": "N/A",
        "attack_type": "kerberoasting",
        "description": "Kerberos TGS ticket extracted for offline cracking. Targets MSSQL service accounts in GOAD AD.",
        "apm_query": (
            "show (spans) SpanName as Name, "
            "SpanAttribute['security.attack.payload'] as SPN "
            "where SpanName like 'ATTACK:KERBEROAST%'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where SpanName like '%KERBEROAST%' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/goad/kerberoast"],
    },
    {
        "id": "SKP-019",
        "name": "DCSync — Domain Controller Replication Attack",
        "severity": "critical",
        "mitre_id": "T1003.006",
        "mitre_tactic": "credential-access",
        "owasp": "N/A",
        "attack_type": "dcsync",
        "description": "DCSync attack simulated to extract NTLM hashes from domain controllers via replication protocol.",
        "apm_query": (
            "show (spans) SpanName as Name "
            "where SpanName like 'ATTACK:DCSYNC%'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where SpanName like '%DCSYNC%' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/goad/dcsync"],
    },
    # ── Enhanced Marketplace (Juice Shop-Inspired) ───────────────
    {
        "id": "SKP-021",
        "name": "Forged Identity — Review Submitted as Another User",
        "severity": "high",
        "mitre_id": "T1078",
        "mitre_tactic": "defense-evasion",
        "owasp": "A01:2021",
        "attack_type": "forged_identity",
        "description": "Product review submitted with a different author name than the authenticated user.",
        "apm_query": (
            "show (spans) SpanName as Name, "
            "SpanAttribute['security.actual_user'] as ActualUser, "
            "SpanAttribute['security.claimed_user'] as ClaimedUser "
            "where SpanAttribute['security.attack.type'] = 'forged_identity'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'forged_identity' "
            "| stats count by security_actual_user, security_claimed_user"
        ),
        "portal_endpoints": ["/portal/api/shop/reviews/{item_id}"],
    },
    {
        "id": "SKP-022",
        "name": "Coupon Forgery — Weak Encoding Exploited",
        "severity": "high",
        "mitre_id": "T1565",
        "mitre_tactic": "impact",
        "owasp": "A02:2021",
        "attack_type": "coupon_forge",
        "description": "Forged coupon submitted using decoded and re-encoded base64 format.",
        "apm_query": (
            "show (spans) SpanAttribute['coupon.forged_code'] as Code, "
            "SpanAttribute['coupon.forged_discount'] as Discount "
            "where SpanAttribute['security.attack.type'] = 'coupon_forge'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'coupon_forge' "
            "| stats count as forge_count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/shop/coupon/apply"],
    },
    {
        "id": "SKP-023",
        "name": "Negative Quantity — Reverse Purchase Fraud",
        "severity": "high",
        "mitre_id": "T1565.002",
        "mitre_tactic": "impact",
        "owasp": "A04:2021",
        "attack_type": "negative_quantity",
        "description": "Negative quantity or amount exploited to reverse financial transactions.",
        "apm_query": (
            "show (spans) SpanAttribute['shop.quantity'] as Quantity, "
            "SpanAttribute['wallet.negative_amount'] as Amount "
            "where SpanAttribute['security.attack.type'] = 'negative_quantity' "
            "or SpanAttribute['security.attack.subtype'] = 'negative_quantity'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'negative_quantity' "
            "or security_attack_type = 'negative_transfer' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/shop/purchase-enhanced", "/portal/api/wallet/transfer"],
    },
    {
        "id": "SKP-024",
        "name": "Price Tampering — Client-Side Price Override",
        "severity": "high",
        "mitre_id": "T1565.002",
        "mitre_tactic": "impact",
        "owasp": "A04:2021",
        "attack_type": "price_tampering",
        "description": "Purchase request included client-supplied price overriding server-side value.",
        "apm_query": (
            "show (spans) SpanAttribute['shop.original_price'] as OriginalPrice, "
            "SpanAttribute['shop.tampered_price'] as TamperedPrice "
            "where SpanAttribute['security.attack.type'] = 'price_tampering'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'price_tampering' "
            "| stats count by security_source_ip, shop_original_price, shop_tampered_price"
        ),
        "portal_endpoints": ["/portal/api/shop/purchase-enhanced"],
    },
    {
        "id": "SKP-025",
        "name": "XXE — XML External Entity in Trade Import",
        "severity": "critical",
        "mitre_id": "T1190",
        "mitre_tactic": "initial-access",
        "owasp": "A05:2021",
        "attack_type": "xxe",
        "description": "XML external entity injection in trade import endpoint, enabling file read or SSRF.",
        "apm_query": (
            "show (spans) SpanAttribute['security.xxe.body_snippet'] as XMLSnippet "
            "where SpanAttribute['security.attack.type'] = 'xxe'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'xxe' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/trade/import"],
    },
    {
        "id": "SKP-026",
        "name": "CSRF — Allegiance Change Without Token",
        "severity": "high",
        "mitre_id": "T1185",
        "mitre_tactic": "collection",
        "owasp": "A01:2021",
        "attack_type": "csrf",
        "description": "Cross-site request forgery on allegiance change — no CSRF token validated.",
        "apm_query": (
            "show (spans) SpanAttribute['security.csrf.referer'] as Referer, "
            "SpanAttribute['security.csrf.origin'] as Origin "
            "where SpanAttribute['security.attack.type'] = 'csrf'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'csrf' "
            "| stats count by security_source_ip, security_csrf_referer"
        ),
        "portal_endpoints": ["/portal/api/users/change-allegiance"],
    },
    {
        "id": "SKP-027",
        "name": "OSINT Password Reset — Security Question Bypass",
        "severity": "high",
        "mitre_id": "T1110.001",
        "mitre_tactic": "credential-access",
        "owasp": "A07:2021",
        "attack_type": "security_question_bypass",
        "description": "Password reset via security question with publicly known GoT trivia answer.",
        "apm_query": (
            "show (spans) SpanAttribute['security.reset.username'] as User, "
            "SpanAttribute['security.reset.method'] as Method "
            "where SpanAttribute['security.attack.type'] = 'security_question_bypass'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'security_question_bypass' "
            "or security_attack_type = 'password_reset_osint' "
            "| stats count by security_source_ip, security_username"
        ),
        "portal_endpoints": ["/portal/api/auth/reset-password-security"],
    },
    {
        "id": "SKP-028",
        "name": "Privilege Escalation — Hidden Role in Registration",
        "severity": "critical",
        "mitre_id": "T1068",
        "mitre_tactic": "privilege-escalation",
        "owasp": "A04:2021",
        "attack_type": "privilege_escalation",
        "description": "User registered with admin role via hidden 'role' parameter in registration request.",
        "apm_query": (
            "show (spans) SpanAttribute['security.escalation.role'] as Role, "
            "SpanAttribute['security.escalation.username'] as User "
            "where SpanAttribute['security.attack.type'] = 'privilege_escalation'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'privilege_escalation' "
            "| stats count by security_source_ip, security_escalation_role"
        ),
        "portal_endpoints": ["/portal/api/auth/register-enhanced"],
    },
    {
        "id": "SKP-029",
        "name": "CAPTCHA Bypass — Anti-Automation Defeated",
        "severity": "medium",
        "mitre_id": "T1185",
        "mitre_tactic": "collection",
        "owasp": "A07:2021",
        "attack_type": "captcha_bypass",
        "description": "Feedback submitted without solving CAPTCHA — answer leaked in API response.",
        "apm_query": (
            "show (spans) SpanAttribute['security.captcha.skipped'] as Skipped "
            "where SpanAttribute['security.attack.type'] = 'captcha_bypass'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'captcha_bypass' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/feedback"],
    },
    {
        "id": "SKP-030",
        "name": "Prototype Pollution — Config Deep Merge Exploit",
        "severity": "critical",
        "mitre_id": "T1059",
        "mitre_tactic": "execution",
        "owasp": "A03:2021",
        "attack_type": "prototype_pollution",
        "description": "Prototype pollution via __proto__ or constructor keys in config update deep merge.",
        "apm_query": (
            "show (spans) SpanAttribute['security.pollution.keys'] as PollutionKeys "
            "where SpanAttribute['security.attack.type'] = 'prototype_pollution'"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_type = 'prototype_pollution' "
            "| stats count by security_source_ip"
        ),
        "portal_endpoints": ["/portal/api/config/update"],
    },
    # ── Meta / Aggregate Rules ────────────────────────────────────
    {
        "id": "SKP-020",
        "name": "Multi-Stage Attack Chain — Reconnaissance to Exploitation",
        "severity": "critical",
        "mitre_id": "T1190",
        "mitre_tactic": "multiple",
        "owasp": "N/A",
        "attack_type": "multi_stage",
        "description": "Single source IP triggered multiple vulnerability types, indicating systematic attack chain.",
        "apm_query": (
            "show (spans) SpanAttribute['security.source_ip'] as SourceIP, "
            "SpanAttribute['security.attack.type'] as AttackType "
            "where SpanAttribute['security.attack.detected'] = 'true' "
            "| stats distinctcount(AttackType) as attack_types by SourceIP "
            "| where attack_types >= 3"
        ),
        "la_query": (
            "'Log Source' = 'OCI APM Trace' "
            "| where security_attack_detected = 'true' "
            "| stats distinctcount(security_attack_type) as attack_types, "
            "count as total_attacks by security_source_ip "
            "| where attack_types >= 3"
        ),
        "portal_endpoints": ["(all portal endpoints)"],
    },
]


def get_rules_by_severity(severity: str) -> list[dict]:
    return [r for r in DETECTION_RULES if r["severity"] == severity]


def get_rules_by_mitre_tactic(tactic: str) -> list[dict]:
    return [r for r in DETECTION_RULES if r["mitre_tactic"] == tactic]


def get_rules_by_owasp(category: str) -> list[dict]:
    return [r for r in DETECTION_RULES if category in r["owasp"]]
