#!/usr/bin/env bash
# C1: Deploy infrastructure — VCN, subnets, gateways, NSGs via Terraform.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$ROOT_DIR/deploy/terraform/environments/dev"

echo "=== C1: Infrastructure Deployment ==="

# Validate required env vars
: "${OCI_COMPARTMENT_ID:?OCI_COMPARTMENT_ID is required}"
: "${OCI_REGION:?OCI_REGION is required}"

OCI_PROFILE="${OCI_PROFILE:-DEFAULT}"
APP_DEPLOY_MODE="${APP_DEPLOY_MODE:-oke}"

# Determine if OKE subnets are needed
CREATE_OKE_SUBNETS="false"
if [[ "$APP_DEPLOY_MODE" == "oke" ]]; then
    CREATE_OKE_SUBNETS="true"
fi

# Check for GOAD peering
ENABLE_GOAD_PEERING="${DEPLOY_GOAD:-true}"

echo "  Region:           $OCI_REGION"
echo "  Profile:          $OCI_PROFILE"
echo "  Compartment:      ${OCI_COMPARTMENT_ID:0:40}..."
echo "  App mode:         $APP_DEPLOY_MODE"
echo "  OKE subnets:      $CREATE_OKE_SUBNETS"
echo "  GOAD peering:     $ENABLE_GOAD_PEERING"

# Check Terraform is installed
if ! command -v terraform &>/dev/null; then
    echo "ERROR: terraform not found. Install: brew install terraform"
    exit 1
fi

# Generate terraform.tfvars
TFVARS="$TF_DIR/terraform.tfvars"
cat > "$TFVARS" <<EOF
# Auto-generated by deploy_infra.sh — do not edit manually
compartment_id     = "$OCI_COMPARTMENT_ID"
region             = "$OCI_REGION"
oci_profile        = "$OCI_PROFILE"
tenancy_ocid       = "${OCI_TENANCY_ID:-}"
project_name       = "skp"
environment        = "${ENVIRONMENT:-production}"
create_oke_subnets = $CREATE_OKE_SUBNETS
enable_goad_peering = $ENABLE_GOAD_PEERING

vcn_cidr              = "10.0.0.0/16"
public_subnet_cidr    = "10.0.1.0/24"
private_subnet_cidr   = "10.0.2.0/24"
oke_api_subnet_cidr   = "10.0.3.0/24"
dns_label             = "skpvcn"
EOF

echo "  Generated: $TFVARS"

# Terraform init + apply
cd "$TF_DIR"
echo "  Running terraform init..."
terraform init -upgrade -input=false

echo "  Running terraform plan..."
terraform plan -out=tfplan -input=false

echo "  Running terraform apply..."
terraform apply -auto-approve tfplan
rm -f tfplan

# Capture outputs and write to .env.local
echo "  Capturing Terraform outputs..."
VCN_OCID=$(terraform output -raw vcn_id 2>/dev/null || echo "")
PUBLIC_SUBNET_OCID=$(terraform output -raw public_subnet_id 2>/dev/null || echo "")
PRIVATE_SUBNET_OCID=$(terraform output -raw private_subnet_id 2>/dev/null || echo "")
APP_NSG_OCID=$(terraform output -raw app_nsg_id 2>/dev/null || echo "")
LB_NSG_OCID=$(terraform output -raw lb_nsg_id 2>/dev/null || echo "")
PRIVATE_RT_OCID=$(terraform output -raw private_route_table_id 2>/dev/null || echo "")

# Write outputs to .env.local
ENV_FILE="$ROOT_DIR/.env.local"
_update_env() {
    local key="$1" val="$2"
    if [[ -z "$val" ]]; then return; fi
    if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
        sed -i.bak "s|^${key}=.*|${key}=${val}|" "$ENV_FILE"
        rm -f "${ENV_FILE}.bak"
    else
        echo "${key}=${val}" >> "$ENV_FILE"
    fi
}

# Create .env.local from example if it doesn't exist
if [[ ! -f "$ENV_FILE" ]]; then
    if [[ -f "$ROOT_DIR/.env.example" ]]; then
        cp "$ROOT_DIR/.env.example" "$ENV_FILE"
    else
        touch "$ENV_FILE"
    fi
fi

_update_env "VCN_OCID" "$VCN_OCID"
_update_env "PUBLIC_SUBNET_OCID" "$PUBLIC_SUBNET_OCID"
_update_env "PRIVATE_SUBNET_OCID" "$PRIVATE_SUBNET_OCID"
_update_env "APP_NSG_OCID" "$APP_NSG_OCID"
_update_env "LB_NSG_OCID" "$LB_NSG_OCID"
_update_env "PRIVATE_ROUTE_TABLE_OCID" "$PRIVATE_RT_OCID"

# If GOAD peering is enabled, capture LPG OCID
if [[ "$ENABLE_GOAD_PEERING" == "true" ]]; then
    APP_LPG_OCID=$(terraform output -raw app_lpg_id 2>/dev/null || echo "")
    if [[ -n "$APP_LPG_OCID" ]]; then
        _update_env "APP_LPG_OCID" "$APP_LPG_OCID"
    fi
fi

echo ""
echo "  Infrastructure deployed successfully!"
echo "    VCN:            ${VCN_OCID:0:40}..."
echo "    Public subnet:  ${PUBLIC_SUBNET_OCID:0:40}..."
echo "    Private subnet: ${PRIVATE_SUBNET_OCID:0:40}..."
