#!/usr/bin/env bash
# C2: Deploy GOADv3 Active Directory Lab — Terraform for VMs + LPG peering.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$ROOT_DIR/goad/terraform"

echo "=== C2: GOADv3 Terraform Deployment ==="

# Validate
: "${OCI_COMPARTMENT_ID:?OCI_COMPARTMENT_ID is required}"
: "${OCI_REGION:?OCI_REGION is required}"
: "${VCN_OCID:?VCN_OCID is required (deploy C1 first)}"

OCI_PROFILE="${OCI_PROFILE:-DEFAULT}"
SSH_PUBLIC_KEY_PATH="${SSH_PUBLIC_KEY_PATH:-$HOME/.ssh/id_rsa.pub}"

if [[ ! -f "$SSH_PUBLIC_KEY_PATH" ]]; then
    echo "ERROR: SSH public key not found: $SSH_PUBLIC_KEY_PATH"
    echo "  Generate with: ssh-keygen -t rsa -b 4096"
    exit 1
fi

SSH_PUBLIC_KEY=$(cat "$SSH_PUBLIC_KEY_PATH")

echo "  Region:           $OCI_REGION"
echo "  Profile:          $OCI_PROFILE"
echo "  App VCN:          ${VCN_OCID:0:40}..."

# Check Terraform
if ! command -v terraform &>/dev/null; then
    echo "ERROR: terraform not found"
    exit 1
fi

# Discover availability domain
AD=$(oci iam availability-domain list \
    --profile "$OCI_PROFILE" \
    --compartment-id "$OCI_COMPARTMENT_ID" \
    --query 'data[0].name' --raw-output 2>/dev/null || echo "")

if [[ -z "$AD" ]]; then
    echo "ERROR: Could not discover availability domain"
    exit 1
fi
echo "  Availability Domain: $AD"

# Generate provider.tf for standalone usage (when used as a module, caller provides provider)
PROVIDER_FILE="$TF_DIR/provider.tf"
cat > "$PROVIDER_FILE" <<EOF
# Auto-generated by deploy_goad.sh — standalone provider configuration.
# When goad/terraform is used as a module (e.g., from stack/main.tf), this file
# should not exist — the calling module provides the provider.

provider "oci" {
  config_file_profile = "$OCI_PROFILE"
  region              = "$OCI_REGION"
}
EOF
echo "  Generated: $PROVIDER_FILE"

# Generate terraform.tfvars
TFVARS="$TF_DIR/terraform.tfvars"
cat > "$TFVARS" <<EOF
# Auto-generated by deploy_goad.sh
tenancy_ocid        = "${OCI_TENANCY_ID:-}"
compartment_ocid    = "$OCI_COMPARTMENT_ID"
region              = "$OCI_REGION"
oci_profile         = "$OCI_PROFILE"
availability_domain = "$AD"
ssh_authorized_keys = "$SSH_PUBLIC_KEY"

# Peering with app VCN
app_vcn_id  = "$VCN_OCID"
app_lpg_id  = "${APP_LPG_OCID:-}"
EOF

echo "  Generated: $TFVARS"

# Terraform init + apply
cd "$TF_DIR"
echo "  Running terraform init..."
terraform init -upgrade -input=false

echo "  Running terraform plan..."
terraform plan -out=tfplan -input=false

echo "  Running terraform apply..."
terraform apply -auto-approve tfplan
rm -f tfplan

# Capture outputs
JUMPBOX_IP=$(terraform output -raw jumpbox_public_ip 2>/dev/null || echo "")
GOAD_VCN_OCID=$(terraform output -raw goad_vcn_id 2>/dev/null || echo "")
GOAD_LPG_OCID=$(terraform output -raw goad_lpg_id 2>/dev/null || echo "")

# Write to .env.local
ENV_FILE="$ROOT_DIR/.env.local"
_update_env() {
    local key="$1" val="$2"
    if [[ -z "$val" ]]; then return; fi
    if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
        sed -i.bak "s|^${key}=.*|${key}=${val}|" "$ENV_FILE"
        rm -f "${ENV_FILE}.bak"
    else
        echo "${key}=${val}" >> "$ENV_FILE"
    fi
}

_update_env "GOAD_JUMPBOX_IP" "$JUMPBOX_IP"
_update_env "GOAD_VCN_OCID" "$GOAD_VCN_OCID"
_update_env "GOAD_LPG_OCID" "$GOAD_LPG_OCID"

echo ""
echo "  GOAD Terraform deployed successfully!"
echo "    Jumpbox:  $JUMPBOX_IP"
echo "    GOAD VCN: ${GOAD_VCN_OCID:0:40}..."
echo ""
echo "  Next: Run provision_goad_ad.sh for AD provisioning via Ansible"
